[package]
name = "snowprints"
version = "0.2.0"
edition = "2024"

categories = ["data-structures", "network-programming"]
description = "Generate sortable shardarble snowflake IDs across available logical volumes"  
keywords = ["UUID", "snowflake", "id", "distributed", "systems", "64bit", "u64"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/w-lfpup/snowprints-rs"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
